name: spldesigns
favicon: null
layout_spectrum: 0.5733694697264582
typography_spectrum: 0.14153503929264843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2511099297553301
  lightness: 0.36478574573993683
  saturation: 0.6330303051508963
  rhythmicContrast: 0.3880575702060014
purpose: []
